import React from "react";
import Head from "next/head";

export default function Head({ title, description, image }) {
  return (
    <div>
      <Head>
        <title>{title || "Create Next App"}</title>
        <meta
          name="description"
          content={description || "Generated by create next app"}
        />
        <link rel="icon" href={image || "/favicon.ico"} />
      </Head>
    </div>
  );
}
